### ISSUE TITLE
jq: error (at <stdin>:1): Cannot index number with string "node"

### ISSUE THREAD

**Issue by ancienter** [bitnami/bitnami-docker-etcd#12]
```
version: '3'
networks:
  xtradb:
    driver: bridge
services:
  etcd:
    image: bitnami/etcd:3.4.14
    environment:
      - ETCDCTL_API=2
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - ./data/etcd:/bitnami/etcd:rw
    networks:
      - xtradb
  mysql1:
    image: percona/percona-xtradb-cluster:5.7
    container_name: mysql1
    ports:
      - 33061:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=mysql
      - DISCOVERY_SERVICE=etcd:2379
    env_file:
      - .env
    volumes:
      - ./data/mysql1:/var/lib/mysql:rw
    networks:
      - xtradb
    links:
      - etcd
    depends_on:
      - etcd
  mysql2:
    image: percona/percona-xtradb-cluster:5.7
    container_name: mysql2
    ports:
      - 33062:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=mysql
      - DISCOVERY_SERVICE=etcd:2379
    env_file:
      - .env
    volumes:
      - ./data/mysql2:/var/lib/mysql:rw
    networks:
      - xtradb
    links:
      - etcd
    depends_on:
      - etcd
  mysql3:
    image: percona/percona-xtradb-cluster:5.7
    container_name: mysql3
    ports:
      - 33063:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=mysql
      - DISCOVERY_SERVICE=etcd:2379
    env_file:
      - .env
    volumes:
      - ./data/mysql3:/var/lib/mysql:rw
    networks:
      - xtradb
    links:
      - etcd
    depends_on:
      - etcd
  mysql4:
    image: percona/percona-xtradb-cluster:5.7
    container_name: mysql4
    ports:
      - 33064:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=mysql
      - DISCOVERY_SERVICE=etcd:2379
    env_file:
      - .env
    volumes:
      - ./data/mysql4:/var/lib/mysql:rw
    networks:
      - xtradb
    links:
      - etcd
    depends_on:
      - etcd
  mysql5:
    image: percona/percona-xtradb-cluster:5.7
    container_name: mysql5
    ports:
      - 33065:3306
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CLUSTER_NAME=mysql
      - DISCOVERY_SERVICE=etcd:2379
    env_file:
      - .env
    volumes:
      - ./data/mysql5:/var/lib/mysql:rw
    networks:
      - xtradb
    links:
      - etcd
    depends_on:
      - etcd
```
