### ISSUE TITLE
docker-compose restart failed

### ISSUE THREAD

**Issue by DexterQY** [bitnami/bitnami-docker-etcd#33]
I started etcd cluster successfully with docker compose, but I got the following error when I restarted the container

**Steps to reproduce the issue:**

1. docker-compose up -d
2. docker restart etcd3

**Describe the results you received:**

```
etcd 10:59:50.21 Welcome to the Bitnami etcd container
etcd 10:59:50.22 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 10:59:50.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 10:59:50.23
etcd 10:59:50.23 INFO  ==> ** Starting etcd setup **
etcd 10:59:50.24 INFO  ==> Validating settings in ETCD_* env vars..
etcd 10:59:50.24 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 10:59:50.25 INFO  ==> Initializing etcd
etcd 10:59:50.25 INFO  ==> Generating etcd config file using env variables
etcd 10:59:50.26 INFO  ==> Detected data from previous deployments
etcd 10:59:50.27 INFO  ==> Updating member in existing cluster
{"level":"warn","ts":"2022-01-10T10:59:55.290+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002e0a80/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}
Error: context deadline exceeded
```

**Describe the results you expected:**

Restart successful

**Additional information you deem important (e.g. issue happens only occasionally):**

My docker-compose.yml
```yaml
version: "3"

services:
  etcd1:
    image: bitnami/etcd:3.5.1
    container_name: etcd1
    restart: always
    volumes:
      - etcd1_data:/bitnami/etcd
    environment:
      TZ: Asia/Shanghai
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - "23791:2379/tcp"
      - "23801:2380/tcp"
    networks:
      - net-etcd

  etcd2:
    image: bitnami/etcd:3.5.1
    container_name: etcd2
    restart: always
    volumes:
      - etcd2_data:/bitnami/etcd
    environment:
      TZ: Asia/Shanghai
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd2"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - "23792:2379/tcp"
      - "23802:2380/tcp"
    networks:
      - net-etcd

  etcd3:
    image: bitnami/etcd:3.5.1
    container_name: etcd3
    restart: always
    volumes:
      - etcd3_data:/bitnami/etcd
    environment:
      TZ: Asia/Shanghai
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd3" 
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd3:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd3:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - "23793:2379/tcp"
      - "23803:2380/tcp"
    networks:
      - net-etcd

networks:
  net-etcd:
    driver: bridge

volumes:
  etcd1_data:
    driver: local
  etcd2_data:
    driver: local
  etcd3_data:
    driver: local
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:23:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-92-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.909GiB
 Name: qy
 ID: BNUJ:XBEA:TMYT:L4DJ:Y6ZQ:UIHD:VNBY:M6BV:HCP3:LKFG:JJMR:U5HC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://jbuty67v.mirror.aliyuncs.com/
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
