### ISSUE TITLE
[bitnami/etcd] Restore Issues on Kubernetes

### ISSUE THREAD

**Issue by dk-do** [bitnami/bitnami-docker-etcd#7]
**Description**

We have some issues regarding etcd-backup restores on Kubernetes:
The etcd-snapshotter is running every hour. Once a day we copy the data from the etcd-snapshot directory to a backup folder in filesystem to perform a tape backup.

Time by time we are struggeling with restoring data.

**Steps to reproduce the issue:**

1. Copy the db file to /tmp/ to all etcd-0, etcd-1, etcd-2 pods.

2. Run the restore-snapshot command in all pods.
`kubectl exec -it etcd-0 -- etcdctl snapshot restore /tmp/db --name etcd-0 --initial-cluster etcd-0=http://etcd-0.etcd-headless.default.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-headless.default.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-headless.default.svc.cluster.local:2380 --initial-cluster-token etcd-cluster-k8s --initial-advertise-peer-urls http://etcd-0.etcd-headless.default.svc.cluster.local:2380`

3. COPY the restored data from /opt/bitnami/etcd/etcd-0.etcd/member/snap/db to the default data directory: /bitnami/etcd/data/member/snap/

4. Unfortunately it is not possible to change the data dir to the original restore location, because it contains the pod-id in the path: /opt/bitnami/etcd/**etcd-0.etcd**/member/snap/db

5. This is why we copy the restored data to the original path.

6. Scale the statefulset down and up again.

**Describe the results you received:**

Sometimes the restore is working. Sometimes we get these errors:

+ etcd-0 › etcd
etcd-0 etcd ==> Bash debug is off
etcd-0 etcd ==> Detected data from previous deployments...
+ etcd-2 › etcd
etcd-2 etcd ==> Bash debug is off
etcd-2 etcd ==> Detected data from previous deployments...
+ etcd-1 › etcd
etcd-1 etcd ==> Bash debug is off
etcd-1 etcd ==> Detected data from previous deployments...
etcd-2 etcd ==> Cluster not responding!!
etcd-2 etcd ==> There was no snapshot to perform data recovery!!
etcd-1 etcd ==> Cluster not responding!!
etcd-1 etcd ==> There was no snapshot to perform data recovery!!
etcd-0 etcd ==> Cluster not responding!!
etcd-0 etcd ==> There was no snapshot to perform data recovery!!

**Describe the results you expected:**

Always a successful backup restore.

**Version**

etcd: 3.4.9-debian-10-r41

- Output of `docker version`:

```
Docker version 18.09.7, build 2d0083d
```

- Output of `docker info`:

```
Containers: 15
 Running: 14
 Paused: 0
 Stopped: 1
Images: 8
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-106-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 62.6GiB
Name: clust01
ID: 6NVR:VI2E:PLUG:NXWK:5VW6:NVND:JAGN:MFOK:W23D:XTMG:QOVS:OQCW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

- Kubernetes Version:

```
1.18.3
```

**Comment by juan131** [comment]
Hi @dk-do 

Why are you manually restoring the snapshots? I mean, we are already providing mechanisms in the chart to automatically recover them installing a new chart. See https://github.com/bitnami/charts/blob/master/bitnami/etcd/README.md:

Parameter | Description	| Default
-- | -- | --
startFromSnapshot.enabled | Initialize new cluster recovering an existing snapshot | false
startFromSnapshot.existingClaim | PVC containing the existing snapshot | nil
startFromSnapshot.snapshotFilename | Snapshot filename | nil

**Comment by dk-do** [comment]
Maybe we need some best practise advice how to solve the following issues:

1. We had a complete power outage in our data centre. After the K8S cluster was available again, everything was fine (MongoDB, ELK, Redis etc.) except etcd. After executing 

`etcdctl endpoint status --endpoints=http://etcd-2.etcd-headless.default.svc.cluster.local:2380,http://etcd-1.etcd-headless.default.svc.cluster.local:2380,http://etcd-0.etcd-headless.default.svc.cluster.local:2380 -w table`

we realized that the database had a size about only 20kb (8MB before). We restarted everything and again we had an "empty" database. To solve the issue we wanted to restore the backup.

2. In addition we have a debug-environment in our network. If we face some problems in our QA-stage we transfer all databases (Mongo, Elastic, PSQL, etcd, Redis) to our dev-stage to investigate the problem.

**Comment by mjrepo2** [comment]
I am having a similar issue, I have the same environment as @dk-do,

I have provided a RWX volume for the snapshotter that is mounted in all etcd pods, I have confirmed that it is mounted in my new test cluster.
Upon attempting to start this new etcd cluster with the the mechanism you mentioned @juan131, I get the same result as dk-do.

`helm install test -f etcd.yaml bitnami/etcd   --set statefulset.replicaCount=3   --set persistence.enable=true   --set persistence.size=8Gi   --set startFromSnapshot.enabled=true   --set startFromSnapshot.existingClaim=etcd-snapshotter  --set startFromSnapshot.snapshotFilename=/snapshots/db-test`

It seems I am having trouble with this part of the setup.sh:

```
if [[ ! -d "$ETCD_DATA_DIR" ]]; then
    echo "==> Creating data dir..." 1>&3 2>&4
    echo "==> There is no data at all. Initializing a new member of the cluster..." 1>&3 2>&4
    store_member_id & 1>&3 2>&4
    configure_rbac
else
    echo "==> Detected data from previous deployments..." 1>&3 2>&4
    if [[ 3 -eq 1 ]]; then
        echo "==> Single node cluster detected!!" 1>&3 2>&4
    elif is_disastrous_failure; then
        echo "==> Cluster not responding!!" 1>&3 2>&4
        latest_snapshot_file="$(find /snapshots/ -maxdepth 1 -type f -name 'db-*' | sort | tail -n 1)"
        if [[ "${latest_snapshot_file}" != "" ]]; then
            echo "==> Restoring etcd cluster from snapshot..." 1>&3 2>&4

            rm -rf $ETCD_DATA_DIR 1>&3 2>&4
            etcdctl snapshot restore "${latest_snapshot_file}" \
              --name $ETCD_NAME \
              --data-dir $ETCD_DATA_DIR \
              --initial-cluster $ETCD_INITIAL_CLUSTER \
              --initial-cluster-token $ETCD_INITIAL_CLUSTER_TOKEN \
              --initial-advertise-peer-urls $ETCD_INITIAL_ADVERTISE_PEER_URLS 1>&3 2>&4
            store_member_id & 1>&3 2>&4
        else
            echo "==> There was no snapshot to perform data recovery!!" 1>&3 2>&4
            exit 1
        fi
    elif should_add_new_member; then
        echo "==> Adding new member to existing cluster..." 1>&3 2>&4
        etcdctl $AUTH_OPTIONS member add "$HOSTNAME" --peer-urls="http://${HOSTNAME}.etcd-headless.default.svc.cluster.local:2380" | grep "^ETCD_" > "$ETCD_DATA_DIR/new_member_envs" 1>&3 2>&4
        sed -ie 's/^/export /' "$ETCD_DATA_DIR/new_member_envs"
        echo "==> Loading env vars of existing cluster..." 1>&3 2>&4
        source "$ETCD_DATA_DIR/new_member_envs" 1>&3 2>&4
        store_member_id & 1>&3 2>&4
    else
        echo "==> Updating member in existing cluster..." 1>&3 2>&4
        etcdctl $AUTH_OPTIONS member update "$(cat "$ETCD_DATA_DIR/member_id")" --peer-urls="http://${HOSTNAME}.etcd-headless.default.svc.cluster.local:2380" 1>&3 2>&4
    fi
fi

```
Although when I manually execute the "find snapshot" part, I see my snapshot.

```
I have no name!@etcd-0:/scripts$ find /snapshots/ -maxdepth 1 -type f -name 'db-*' | sort | tail -n 1
->
/snapshots/db-test

```
However - the end result is still:

```
kubectl logs test-etcd-0 -p
==> Bash debug is on
==> Creating data dir...
==> There is no data at all. Initializing a new member of the cluster...
==> There was no snapshot to perform data recovery!!

```
If there is any more info I can provide, please let me know as this is halting our using ETCD.

**Comment by juan131** [comment]
Hi everyone,

I tried to reproduce the issue without luck:

```
$ helm install etcd bitnami/etcd --set statefulset.replicaCount=3 --set disasterRecovery.enabled=true --set disasterRecovery.cronjob.schedule="*/5 * * * *"
$ kubectl get pvc
NAME                                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-etcd-0                                           Bound    pvc-cf424839-da82-4d93-8a39-bb3f9637ff49   8Gi        RWO            standard       8m1s
data-etcd-1                                           Bound    pvc-e42c9a96-4369-4f06-b436-5c309deaf156   8Gi        RWO            standard       8m1s
data-etcd-2                                           Bound    pvc-eddf6ba3-866a-45b1-90fb-697be91e42f4   8Gi        RWO            standard       8m1s
etcd-snapshotter                                      Bound    pvc-ba98bae5-f6dd-46d9-a5ba-7a7634c7f1e2   2Gi        RWX            nfs            8m2s
```

Once I had my 1st backup, I created a pod (using the manifests below) to copy the latest snapshot in a different PVC:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: snapshots
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
---
apiVersion: v1
kind: Pod
metadata:
  name: copy-pvc
spec:
  volumes:
    - name: original-snapshots
      persistentVolumeClaim:
        claimName: etcd-snapshotter
    - name: snapshots
      persistentVolumeClaim:
        claimName: snapshots
  containers:
    - name: inspector
      image: bitnami/minideb
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: "/original-snapshots"
          name: original-snapshots
        - mountPath: "/snapshots"
          name: snapshots
```

```console
$ kubectl create -f copy-snapshost.yaml
persistentvolumeclaim/snapshots created
pod/copy-pvc created
$ kubectl exec -it copy-pvc -- bash
$ ls -la /original-snapshots/
total 56
drwxrwsrwx 2 root root  4096 Jul 16 07:40 .
drwxr-xr-x 1 root root  4096 Jul 16 07:41 ..
-rw------- 1 1001 root 20512 Jul 16 07:35 db-2020-07-16_07-35
-rw------- 1 1001 root 20512 Jul 16 07:40 db-2020-07-16_07-40
$ cp /original-snapshots/db-2020-07-16_07-40 /snapshots/
$ chown 1001 /snapshots/db-2020-07-16_07-40
```

Then, I uninstalled etcd:

```console
$ krm pod/copy-pvc
$ helm uninstall etcd
$ krm pvc data-etcd-0 data-etcd-1 data-etcd-2
persistentvolumeclaim "data-etcd-0" deleted
persistentvolumeclaim "data-etcd-1" deleted
persistentvolumeclaim "data-etcd-2" deleted
```

Finally, I installed etcd again, using the "snapshots" PVC to start etcd:

```console
$ helm install etcd bitnami/etcd --set statefulset.replicaCount=3 --set startFromSnapshot.enabled=true --set startFromSnapshot.existingClaim=snapshots --set startFromSnapshot.snapshotFilename=db-2020-07-16_07-40
$ kubectl logs -f etcd-0
...
==> Initializing member by restoring etcd cluster from snapshot...
{"level":"info","ts":1594886235.8186045,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd-0.etcd-headless.default.svc.cluster.local:2380","host":"etcd-0.etcd-headless.default.svc.cluster.local:2380","resolved-addr":"10.32.2.32:2380"}
{"level":"info","ts":1594886235.8188918,"caller":"netutil/netutil.go:112","msg":"resolved URL Host","url":"http://etcd-0.etcd-headless.default.svc.cluster.local:2380","host":"etcd-0.etcd-headless.default.svc.cluster.local:2380","resolved-addr":"10.32.2.32:2380"}
{"level":"info","ts":1594886235.8189979,"caller":"snapshot/v3_snapshot.go:296","msg":"restoring snapshot","path":"/init-snapshot/db-2020-07-16_07-40","wal-dir":"/bitnami/etcd/data/member/wal","data-dir":"/bitnami/etcd/data","snap-dir":"/bitnami/etcd/data/member/snap"}
{"level":"info","ts":1594886235.830253,"caller":"membership/cluster.go:392","msg":"added member","cluster-id":"9e98e654be1e22d7","local-member-id":"0","added-peer-id":"45a18acb10aa275e","added-peer-peer-urls":["http://etcd-2.etcd-headless.default.svc.cluster.local:2380"]}
```

**Comment by mjrepo2** [comment]
Hello @juan131, I was able to successfully restore a cluster with the method you posted.
Not sure why it wasn't working for me the first few tries, my helm install command isn't soo much different.

**Comment by juan131** [comment]
That's great! I'm glad you were able to restore the cluster @mjrepo2 

@dk-do could you please also give a try to the instructions I shared?

**Comment by mjrepo2** [comment]
> That's great! I'm glad you were able to restore the cluster @mjrepo2
> 
> @dk-do could you please also give a try to the instructions I shared?

We are in the same office, I believe this can be closed.

**Comment by mjrepo2** [comment]
I have run into another issue:
When restoring our etcd we have to keep the same deployment name (for connection strings and such), I have noticed when I try to restore a second time, upon _helm delete etcd_, my PVC for etcd-snapshotter is released, and will not be remounted, since a new PVC/PV for etcd-snapshotter is created.. Is this due to it being labelled as an "init-snapshot-volume" like so ->

  init-snapshot-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  etcd-snapshotter
    ReadOnly:   false
  snapshot-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  etcd-snapshotter
    ReadOnly:   false

Upon restoring ETCD, a new etcd-snapshotter pvc is created, which is by default empty, and no restore is triggered.
Pod description contains no errors, and the pods are stuck in ContainerCreating

```
Events:
  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Warning  FailedScheduling        3s (x3 over 5s)  default-scheduler        running "VolumeBinding" filter plugin for pod "etcd-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               0s               default-scheduler        Successfully assigned default/etcd-0 to ops-w3
  Normal   SuccessfulAttachVolume  0s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-220655f1-36e5-46ef-9bc5-7a3421d49c83"
  Normal   SuccessfulAttachVolume  0s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-984e66c6-e419-45f9-8403-15e7acb04fe7"
```
![image](https://user-images.githubusercontent.com/48012528/88050941-151cf000-cb58-11ea-82c7-9ad170d1c2c8.png)

**Comment by juan131** [comment]
HI @mjrepo2 

> When restoring our etcd we have to keep the same deployment name (for connection strings and such), I have noticed when I try to restore a second time, upon helm delete etcd, my PVC for etcd-snapshotter is released, and will not be remounted, since a new PVC/PV for etcd-snapshotter is created.. Is this due to it being labelled as an "init-snapshot-volume" like so 

I'm a little bit confused... Could you please share the exact commands you used? I don't fully understand what you mean with restoring it for a second time.

**Comment by mjrepo2** [comment]
Hey @juan131 

I guess my question would be simpler when I word it like this: 

Is there any way to restore an etcd cluster from the volume that is created from disaster recovery, etcd-snapshotter? Or do I have to always provide another extra volume for that? It seems overkill that I have a volume for each etcd instance, a volume to snapshot the cluster, and another volume to restore?

**Comment by juan131** [comment]
Yes, I agree. We should be able reuse the volume used by `etcd-snapshotter` to restore the cluster too. Regardless you can also use a different one. That said, it's not possible with the current implementation.

I'll create a task to work on it. Thanks for the feedback.

**Comment by haroonb** [comment]
@juan131 Hi, I wanted to automate the task of restoring from a backup and was wondering if It's possible to point to a local file instead of a mounted pv?

**Comment by juan131** [comment]
Hi @haroonb 

> was wondering if It's possible to point to a local file instead of a mounted pv?

I guess you can do it in 4 steps:

- Create the PV
- Create a pod with some container that does nothing (e.g. `sleep infinity) and mount the PV on it. Check this comment that does sth similar https://github.com/bitnami/bitnami-docker-etcd/issues/7#issuecomment-659230065
- Use `kubectl cp` to copy your local snapshot to the container (in the path where you mounted the PV) 
- Delete the pod

Now you have a PV containing your local snapshot.

**Comment by haroonb** [comment]
Hello @juan131 

I tried to create a volume with a nfs mount, which has me etcd backups, instead of creating a new volume and copying files into that, but etcd doesn't find the files. The command I use to restore the backup is `helm install --set image.tag=3.4.9-debian-10-r46 -f values.yaml  etcd bitnami/etcd --set statefulset.replicaCount=3 --set startFromSnapshot.enabled=true --set startFromSnapshot.existingClaim=restore --set startFromSnapshot.snapshotFilename=db --version 4.8.10`

If I run a test pod I can see the data is accessible through a test pod and does show up in the etcd pods, but etcd can't seem to find the backup.


```
              kind: PersistentVolume
              api_version: v1
              metadata:
                name: restore
                labels:
                  application: restore
              spec:
                storageClassName: rook-ceph-fs
                capacity:
                  storage: 100Mi
                accessModes:
                  - ReadWriteMany
                mountOptions:
                  - hard
                  - rw
                nfs:
                  path: "{{ restore_path }}"
                  server: "{{ cluster_network | ipmath(master_ip) }}"
---
              kind: PersistentVolumeClaim
              api_version: v1
              metadata:
                namespace: default
                name: restore
                labels:
                  application: restore
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 100Mi
                storageClassName: rook-ceph-fs
                selector:
                  matchLabels:
                    application: restore

```

**Comment by juan131** [comment]
Hello @haroonb 

Please create a pod like the one below, so you can inspect what you have in the "restore" PV:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: inspect-pv
spec:
  volumes:
    - name: snapshots
      persistentVolumeClaim:
        claimName: restore
  containers:
    - name: inspector
      image: bitnami/minideb
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: "/snapshots"
          name: restore
```

Then, access the Pod and inspect the volume:

```console
$ kubectl exec -it inspect-pv -- ls -la /original-snapshots/
```

Please share the output of the above command.

**Comment by haroonb** [comment]
Hello the output of the command is.

```
user@master1:~/etcd$ kubectl exec -it inspect-pv -- ls -la /snapshots/
total 4124
drw------- 2 1001 1000    4096 Jul 29 11:09 .
drwxr-xr-x 1 root root    4096 Jul 30 06:54 ..
-rw------- 1 1001 root 4210720 Jul 29 11:05 db
```

Thanks for your assistance.

**Comment by juan131** [comment]
Hi @haroonb 

The "restore" PV seems to be fine.

Could you try re-installing the chart using the latest chart version? Please remember to uninstall the previous release previously and remove the PVC(s) generated during the previous installation.

```console
$ helm repo update
$ helm install --set image.tag=3.4.9-debian-10-r46 -f values.yaml  etcd bitnami/etcd \
    --set statefulset.replicaCount=3 \
    --set startFromSnapshot.enabled=true \
    --set startFromSnapshot.existingClaim=restore \
    --set startFromSnapshot.snapshotFilename=db
```

Then, share the logs of any of the etcd replicas (e.g. `etcd-0`):

```
$ kubectl logs -f etcd-0 -c etcd
```

**Comment by haroonb** [comment]
The output of the command is as following.

```
user@master1:~/etcd$ helm install --set image.tag=3.4.9-debian-10-r46 -f values.yaml  etcd bitnami/etcd \
>     --set statefulset.replicaCount=3 \
>     --set startFromSnapshot.enabled=true \
>     --set startFromSnapshot.existingClaim=restore \
>     --set startFromSnapshot.snapshotFilename=db
NAME: etcd
LAST DEPLOYED: Thu Jul 30 07:06:51 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

etcd can be accessed via port 2379 on the following DNS name from within your cluster:

    etcd.default.svc.cluster.local

To set a key run the following command:

    export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=etcd,app.kubernetes.io/instance=etcd" -o jsonpath="{.items[0].metadata.name}")
    kubectl exec -it $POD_NAME -- etcdctl put /message Hello

To get a key run the following command:

    export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=etcd,app.kubernetes.io/instance=etcd" -o jsonpath="{.items[0].metadata.name}")
    kubectl exec -it $POD_NAME -- etcdctl get /message

To connect to your etcd server from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/etcd 2379:2379 &
    echo "etcd URL: http://127.0.0.1:2379"
```


```
user@master1:~/etcd$ kubectl logs -f etcd-0 -c etcd
==> Bash debug is off
==> Creating data dir...
==> There is no data at all. Initializing a new member of the cluster...
==> There was no snapshot to perform data recovery!!
```

**Comment by juan131** [comment]
Please also run the commands below and share the output:

```console
$ kubectl get etcd-0 pod -o yaml 
$ kubectl get cm etcd-scripts -o yaml 
```

**Comment by haroonb** [comment]
The results can be viewed here.

http://ix.io/2sFP

**Comment by juan131** [comment]
This is the piece of code throwing the logs you shared:

```bash
        if [[ -f "/init-snapshot/db" ]]; then
            echo "==> Initializing member by restoring etcd cluster from snapshot..." 1>&3 2>&4
            etcdctl snapshot restore /init-snapshot/db \
              --name $ETCD_NAME \
              --initial-cluster $ETCD_INITIAL_CLUSTER \
              --initial-cluster-token $ETCD_INITIAL_CLUSTER_TOKEN \
              --initial-advertise-peer-urls $ETCD_INITIAL_ADVERTISE_PEER_URLS \
              --data-dir $ETCD_DATA_DIR 1>&3 2>&4
            store_member_id & 1>&3 2>&4
        else
            echo "==> There was no snapshot to perform data recovery!!" 1>&3 2>&4
            exit 1
        fi
```

So it's basically not finding the file `/init-snapshot/db`. If we take a look to the pod definition, we can see this:

```yaml
...
    volumeMounts:
    ...
    - mountPath: /init-snapshot
      name: init-snapshot-volume
  ...
  volumes:
  ...
  - name: init-snapshot-volume
    persistentVolumeClaim:
      claimName: restore
```

So basically it's mounting the "restore" PV at `/init-snapshot`. Therefore, it should be detecting the snapshot file you have... It's so weird
