### ISSUE TITLE
Volumes in Kubernetes permission deny

### ISSUE THREAD

**Issue by mogody** [bitnami/bitnami-docker-etcd#8]
I deployed etcd on k8s, and the securityContext has been configured according to the documentation, but it still prompts no permission：
https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html

this is my config:
```
spec:
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
        containers:
        - image: bitnami/nginx:latest
          name: nginx
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
```

Finally change it like this，and work fine:
```
 spec:
        initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R g+rwX /bitnami']
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
        containers:
        - image: bitnami/nginx:latest
          name: nginx
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
```

why use securityContext cant working?

**Comment by marcosbc** [comment]
@mogody In the docs, we recommend to use an init-container to change the permissions of the volume before mounting it:

```
      spec:
        initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R g+rwX /bitnami']
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
        containers:
        - image: bitnami/nginx:latest
          name: nginx
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
```

As an init-container, it will be executed before the other ones:

```
      spec:
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
        containers:
        - image: bitnami/nginx:latest
          name: nginx
          volumeMounts:
          - mountPath: /bitnami
            name: nginx-data
```

Note that your Kubernetes template would need to include **both** the init-container, and the container specs. 

See the Bitnami Helm chart for etcd if you want to run etcd as a non-root user in Kubernetes: https://github.com/bitnami/charts/tree/master/bitnami/etcd
